[program:mental_dialogue]
command=/var/www/Mental-dialogue-applet/venv/bin/python3 /var/www/Mental-dialogue-applet/Mental-dialogue-applet/psycode_origin/app.py
directory=/var/www/Mental-dialogue-applet/Mental-dialogue-applet/psycode_origin
user=root
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/mental_dialogue.log
stderr_logfile=/var/log/mental_dialogue.err
environment=PYTHONPATH="/var/www/Mental-dialogue-applet/Mental-dialogue-applet/psycode_origin" 